<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        
    }

    function index()
    {
        $data['_view'] = 'dashboard';
        $data['heading'] = 'Editing Dashboard';
        $this->load->view('layouts/main',$data);
    }
    public function logout(){
        //unset($_SESSION);
        
        $this->session->sess_destroy();
        $data['_view'] = 'dashboard';
        $data['heading'] = 'Editing Dashboard';
        $this->load->view('layouts/main',$data);
    }
}
