<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Employees extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Personal_info_model');
        $this->load->model('Faculty_education_model');
        $this->load->model('Faculty_subject_model');
        $this->load->model('Faculty_phd_model');
        $this->load->model('Faculty_publication_model');
        $this->load->model('Faculty_experience_model');
        
    }

    public function all_Employees()
    {
        $data['personal_info'] = $this->Personal_info_model->get_all_personal_info();
        /*$data['faculty_education'] = $this->Faculty_education_model->get_all_faculty_education();
        $data['faculty_subject'] = $this->Faculty_subject_model->get_all_faculty_subject();
        $data['faculty_phd'] = $this->Faculty_phd_model->get_all_faculty_phd();
        $data['faculty_publications'] = $this->Faculty_publication_model->get_all_faculty_publications();
        $data['faculty_experience'] = $this->Faculty_experience_model->get_all_faculty_experience();*/
        $data['_view'] = 'employeesList/index';
        $data['heading'] = 'List of Employees';
        $this->load->view('layouts/main',$data);
    }
    public function getEmployee($emp_id)
    {
        $data['personal_info'] = $this->Personal_info_model->get_info_by_id($emp_id);
        $data['faculty_subject'] = $this->Faculty_subject_model->get_info_by_id($emp_id);
        $data['faculty_publications'] = $this->Faculty_publication_model->get_info_by_id($emp_id);
        $data['faculty_phd'] = $this->Faculty_phd_model->get_info_by_id($emp_id);
        $data['faculty_experience'] = $this->Faculty_experience_model->get_info_by_id($emp_id);
        $data['faculty_education'] = $this->Faculty_education_model->get_info_by_id($emp_id);
        
        $data['_view1'] = 'personal_info/index';
        $data['_view2'] = 'faculty_subject/index';
        $data['_view3'] = 'faculty_publication/index';
        $data['_view4'] = 'faculty_phd/index';
        $data['_view5'] = 'faculty_experience/index';
        $data['_view6'] = 'faculty_education/index';
        
       
        $data['heading1'] = 'personal_info';
        $data['heading2'] = 'faculty_subject';
        $data['heading3'] = 'faculty_publications';
        $data['heading4'] = 'faculty_phd';
        $data['heading5'] = 'faculty_experience';
        $data['heading6'] = 'faculty_education';
        $this->load->view('layouts/main',$data);
    }
}
