<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Faculty_subject extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Faculty_subject_model');
    } 

    /*
     * Listing of faculty_subject
     */
    function index()
    {
        $data['faculty_subject'] = $this->Faculty_subject_model->get_all_faculty_subject();
        $data['heading'] = 'Faculty Subject';
        $data['_view'] = 'faculty_subject/index';
        $this->load->view('layouts/main',$data);
    }
    function faculty_view()
    {
        $data['faculty_subject'] = $this->Faculty_subject_model->get_info_by_id($this->session->userdata('password'));
        $data['heading'] = 'Faculty Subject';
        $data['_view'] = 'faculty_subject/index';
        $this->load->view('layouts/main',$data);
    }
    /*
     * Adding a new faculty_subject
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
                'emp_id' => $_SESSION['emp_id'],
				'subject_name' => $this->input->post('subject_name'),
            );
            
            $faculty_subject_id = $this->Faculty_subject_model->add_faculty_subject($params);
            //redirect('faculty_subject/index');
            if(isset($_SESSION['start-adding']))
            {
                $this->session->set_flashdata('success','Data Stored. Go to next page');
                redirect('faculty_subject/add');
            }
            else 
            {
                redirect('faculty_subject/index');
            }
        }
        else
        {
			$this->load->model('Personal_info_model');
			$data['all_personal_info'] = $this->Personal_info_model->get_all_personal_info();
            $data['heading'] = 'Faculty Subject';
            $data['_view'] = 'faculty_subject/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a faculty_subject
     */
    function edit($id)
    {   
        // check if the faculty_subject exists before trying to edit it
        $data['faculty_subject'] = $this->Faculty_subject_model->get_faculty_subject($id);
        
        if(isset($data['faculty_subject']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'emp_id' => $this->input->post('emp_id'),
					'subject_name' => $this->input->post('subject_name'),
                );

                $this->Faculty_subject_model->update_faculty_subject($id,$params);            
                redirect('faculty_subject/index');
                
            }
            else
            {
				$this->load->model('Personal_info_model');
				$data['all_personal_info'] = $this->Personal_info_model->get_all_personal_info();

                $data['_view'] = 'faculty_subject/edit';
                $data['heading'] = 'Faculty Subject';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The faculty_subject you are trying to edit does not exist.');
    } 

    /*
     * Deleting faculty_subject
     */
    function remove($id)
    {
        $faculty_subject = $this->Faculty_subject_model->get_faculty_subject($id);

        // check if the faculty_subject exists before trying to delete it
        if(isset($faculty_subject['id']))
        {
            $this->Faculty_subject_model->delete_faculty_subject($id);
            redirect('faculty_subject/index');
        }
        else
            show_error('The faculty_subject you are trying to delete does not exist.');
    }
    
}
