<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Faculty_education extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Faculty_education_model');
    } 

    /*
     * Listing of faculty_education
     */
    function index()
    {
        $data['faculty_education'] = $this->Faculty_education_model->get_all_faculty_education();
        $data['heading'] = 'Faculty Education';
        $data['_view'] = 'faculty_education/index';
        $this->load->view('layouts/main',$data);
    }
    function faculty_view()
    {
        $data['faculty_education'] = $this->Faculty_education_model->get_info_by_id($this->session->userdata('password'));
        $data['heading'] = 'Faculty Education';
       $data['_view'] = 'faculty_education/index';
        $this->load->view('layouts/main',$data);
    }
    /*
     * Adding a new faculty_education
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'emp_id' => $this->input->post('emp_id'),
				'Tenth' => $this->input->post('Tenth'),
				'tenth_year_of_study' => $this->input->post('tenth_year_of_study'),
				'twelve_standard' => $this->input->post('twelve_standard'),
				'twelve_year_of_study' => $this->input->post('twelve_year_of_study'),
				'degree' => $this->input->post('degree'),
				'degree_year_of_study' => $this->input->post('degree_year_of_study'),
				'masters' => $this->input->post('masters'),
				'masters_year_of_study' => $this->input->post('masters_year_of_study'),
				'PHD' => $this->input->post('PHD'),
            );
            
            $faculty_education_id = $this->Faculty_education_model->add_faculty_education($params);
            //redirect('faculty_education/index');
            if(isset($_SESSION['start-adding']))
            {
                $this->session->set_flashdata('success','Data Stored. Go to next page');
                redirect('faculty_education/add');
            }
            else 
            {
                redirect('faculty_education/index');
            }
        }
        else
        {
			$this->load->model('Personal_info_model');
			$data['all_personal_info'] = $this->Personal_info_model->get_all_personal_info();
            
            $data['_view'] = 'faculty_education/add';
            $data['heading'] = 'Faculty Education';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a faculty_education
     */
    function edit($id)
    {   
        // check if the faculty_education exists before trying to edit it
        $data['faculty_education'] = $this->Faculty_education_model->get_faculty_education($id);
        
        if(isset($data['faculty_education']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'emp_id' => $this->input->post('emp_id'),
					'Tenth' => $this->input->post('Tenth'),
					'tenth_year_of_study' => $this->input->post('tenth_year_of_study'),
					'twelve_standard' => $this->input->post('twelve_standard'),
					'twelve_year_of_study' => $this->input->post('twelve_year_of_study'),
					'degree' => $this->input->post('degree'),
					'degree_year_of_study' => $this->input->post('degree_year_of_study'),
					'masters' => $this->input->post('masters'),
					'masters_year_of_study' => $this->input->post('masters_year_of_study'),
					'PHD' => $this->input->post('PHD'),
                );

                $this->Faculty_education_model->update_faculty_education($id,$params);            
                redirect('faculty_education/index');
            }
            else
            {
				$this->load->model('Personal_info_model');
				$data['all_personal_info'] = $this->Personal_info_model->get_all_personal_info();

                $data['_view'] = 'faculty_education/edit';
                $data['heading'] = 'Faculty Education';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The faculty_education you are trying to edit does not exist.');
    } 

    /*
     * Deleting faculty_education
     */
    function remove($id)
    {
        $faculty_education = $this->Faculty_education_model->get_faculty_education($id);

        // check if the faculty_education exists before trying to delete it
        if(isset($faculty_education['id']))
        {
            $this->Faculty_education_model->delete_faculty_education($id);
            redirect('faculty_education/index');
        }
        else
            show_error('The faculty_education you are trying to delete does not exist.');
    }
    
}
