<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Faculty_experience extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Faculty_experience_model');
    } 

    /*
     * Listing of faculty_experience
     */
    function index()
    {
        $data['faculty_experience'] = $this->Faculty_experience_model->get_all_faculty_experience();
        $data['heading'] = 'Faculty Experience';
        $data['_view'] = 'faculty_experience/index';
        $this->load->view('layouts/main',$data);
    }
    function faculty_view()
    {
        $data['faculty_experience'] = $this->Faculty_experience_model->get_info_by_id($this->session->userdata('password'));
        $data['heading'] = 'Faculty Experience';
        $data['_view'] = 'faculty_experience/index';
        $this->load->view('layouts/main',$data);
    }
    /*
     * Adding a new faculty_experience
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'emp_id' => $this->input->post('emp_id'),
				'institution_name' => $this->input->post('institution_name'),
				'university' => $this->input->post('university'),
				'teaching_hours' => $this->input->post('teaching_hours'),
				'place' => $this->input->post('place'),
            );
            
            $faculty_experience_id = $this->Faculty_experience_model->add_faculty_experience($params);
            //redirect('faculty_experience/index');
            if(isset($_SESSION['start-adding']))
            {
                $this->session->set_flashdata('success','Data Stored. Go to next page');
                redirect('faculty_experience/add');
            }
            else 
            {
                redirect('faculty_experience/index');
            }
        }
        else
        {
			$this->load->model('Personal_info_model');
			$data['all_personal_info'] = $this->Personal_info_model->get_all_personal_info();
            $data['heading'] = 'Faculty Experience';
            $data['_view'] = 'faculty_experience/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a faculty_experience
     */
    function edit($id)
    {   
        // check if the faculty_experience exists before trying to edit it
        $data['faculty_experience'] = $this->Faculty_experience_model->get_faculty_experience($id);
        
        if(isset($data['faculty_experience']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'emp_id' => $this->input->post('emp_id'),
					'institution_name' => $this->input->post('institution_name'),
					'university' => $this->input->post('university'),
					'teaching_hours' => $this->input->post('teaching_hours'),
					'place' => $this->input->post('place'),
                );

                $this->Faculty_experience_model->update_faculty_experience($id,$params);            
                redirect('faculty_experience/index');
            }
            else
            {
				$this->load->model('Personal_info_model');
				$data['all_personal_info'] = $this->Personal_info_model->get_all_personal_info();

                $data['_view'] = 'faculty_experience/edit';
                $data['heading'] = 'Faculty Experience';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The faculty_experience you are trying to edit does not exist.');
    } 

    /*
     * Deleting faculty_experience
     */
    function remove($id)
    {
        $faculty_experience = $this->Faculty_experience_model->get_faculty_experience($id);

        // check if the faculty_experience exists before trying to delete it
        if(isset($faculty_experience['id']))
        {
            $this->Faculty_experience_model->delete_faculty_experience($id);
            redirect('faculty_experience/index');
        }
        else
            show_error('The faculty_experience you are trying to delete does not exist.');
    }
    
}
