<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class documents_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get faculty_publication by id

    /*
     * Get all faculty_publications
     */
   
    function get_all_faculty_docs($emp_id)
    {
        $this->db->order_by('id', 'desc');
        $this->db->where('emp_id',$emp_id);
        return $this->db->get('documents')->result_array();
    } 
    /*
     * function to add new faculty_publication
     */
    function add_documents($params)
    {
        $this->db->insert('documents',$params);
        return $this->db->insert_id();
    }
    function get_info_by_id($emp_id)
    {
        $this->db->order_by('id', 'desc');
        $this->db->where('emp_id',$emp_id);
        return $this->db->get('documents')->result_array();
    }   
    
   
}
