<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Faculty_experience_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get faculty_experience by id
     */
    function get_faculty_experience($id)
    {
        return $this->db->get_where('faculty_experience',array('id'=>$id))->row_array();
    }
    function get_info_by_id($emp_id)
    {
        $this->db->order_by('id', 'desc');
        $this->db->where('emp_id',$emp_id);
        return $this->db->get('faculty_experience')->result_array();
    } 
    /*
     * Get all faculty_experience
     */
    function get_all_faculty_experience()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('faculty_experience')->result_array();
    }
        
    /*
     * function to add new faculty_experience
     */
    function add_faculty_experience($params)
    {
        $this->db->insert('faculty_experience',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update faculty_experience
     */
    function update_faculty_experience($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('faculty_experience',$params);
    }
    
    /*
     * function to delete faculty_experience
     */
    function delete_faculty_experience($id)
    {
        return $this->db->delete('faculty_experience',array('id'=>$id));
    }
}
