<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Faculty_education_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get faculty_education by id
     */
    function get_faculty_education($id)
    {
        return $this->db->get_where('faculty_education',array('id'=>$id))->row_array();
    }
    function get_info_by_id($emp_id)
    {
        $this->db->order_by('id', 'desc');
        $this->db->where('emp_id',$emp_id);
        return $this->db->get('faculty_education')->result_array();
    }  
    /*
     * Get all faculty_education
     */
    function get_all_faculty_education()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('faculty_education')->result_array();
    }
        
    /*
     * function to add new faculty_education
     */
    function add_faculty_education($params)
    {
        $this->db->insert('faculty_education',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update faculty_education
     */
    function update_faculty_education($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('faculty_education',$params);
    }
    
    /*
     * function to delete faculty_education
     */
    function delete_faculty_education($id)
    {
        return $this->db->delete('faculty_education',array('id'=>$id));
    }
}
