<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Faculty_subject_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get faculty_subject by id
     */
    function get_faculty_subject($id)
    {
        return $this->db->get_where('faculty_subject',array('id'=>$id))->row_array();
    }
    function get_info_by_id($emp_id)
    {
        $this->db->order_by('id', 'desc');
        $this->db->where('emp_id',$emp_id);
        return $this->db->get('faculty_subject')->result_array();
    }  
    /*
     * Get all faculty_subject
     */
    function get_all_faculty_subject()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('faculty_subject')->result_array();
    }
        
    /*
     * function to add new faculty_subject
     */
    function add_faculty_subject($params)
    {
        $this->db->insert('faculty_subject',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update faculty_subject
     */
    function update_faculty_subject($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('faculty_subject',$params);
    }
    
    /*
     * function to delete faculty_subject
     */
    function delete_faculty_subject($id)
    {
        return $this->db->delete('faculty_subject',array('id'=>$id));
    }
}
