<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Personal_info_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get personal_info by id
     */
    function get_personal_info($id)
    {
        return $this->db->get_where('personal_info',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all personal_info
     */
    function get_all_personal_info()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('personal_info')->result_array();
    }
        
    /*
     * function to add new personal_info
     */
    function add_personal_info($params)
    {
        $this->db->insert('personal_info',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update personal_info
     */
    function update_personal_info($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('personal_info',$params);
    }
    
    /*
     * function to delete personal_info
     */
    function delete_personal_info($id)
    {
        return $this->db->delete('personal_info',array('id'=>$id));
    }
}
